apiVersion: v1
kind: Service
metadata:
  name: poc-devops-bk-service
#  namespace: poc-devops
spec:
  ports:
    - name: http
      port: 8080
  type: LoadBalancer
  selector:
    apps: poc-devops-bk-service
