apiVersion: v1
kind: Service
metadata:
  name: poc-devops-bk-service
#  namespace: poc-devops
spec:
  ports:
    - name: http
    #Este target port enmascara el port del cloud endpoint  puerto de entrada y puerto target que resuelve.
      port: 80    
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer
  selector:
    apps: poc-devops-bk-service
